CLASSES = ['Sports & Outdoors',
 'Toys & Games',
 'Office Products',
 'Industrial & Scientific',
 'Arts, Crafts & Sewing',
 'Movies & TV',
 'Computers',
 'Home Audio & Theater',
 'Grocery',
 'Automotive',
 'Pet Supplies',
 'Tools & Home Improvement',
 'Musical Instruments',
 'Health & Personal Care',
 'Amazon Fashion',
 'Digital Music',
 'Amazon Home',
 'All Electronics',
 'Camera & Photo',
 'Cell Phones & Accessories',
 'Books',
 'Video Games']